spring:
  application:
    name: persistence-service
  datasource:
    url: jdbc:mysql://localhost:3306/micro_service_highway?createDatabaseIfNotExist=true
    username: root
    password: Dew@2005
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/