server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: persistenceService
          uri: lb://persistence-service
          predicates:
            - Path=/api/v1/persistence/**
        - id: userService
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: vehicleService
          uri: http://192.168.1.6:8083
          predicates:
            - Path=/api/v1/vehicle/**
        - id: ticketService
          uri: lb://ticket-service
          predicates:
            - Path=/api/v1/ticket/**
        - id: paymentService
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**